---
title: "loc-02-setup"
author: "Kate Morkeski"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load libraries

```{r}

library(here)
library(lubridate)
library(tidyverse)
library(plotly)

```

## read in GPS and other underway data

```{r}

Sys.setenv(TZ='UTC')

combined <- read_csv(here('loc-02-input/loc02_uw_qc_no_TA.csv')) 

#combined$datetime_utc <- as.POSIXct(combined$datetime_utc, tz = "UTC", format="%d-%b-%Y %H:%M:%OS")

met <- read_delim(here('loc-02-input/Metdat.dat'), skip = 1)

pressure <- met |> select(TIMESTAMP, BaroPress)  

pressure <- pressure |> rename(BaroPress_hPa = BaroPress) 
pressure <- pressure[-1,]
pressure <- pressure[-1,]

#format columns as date and time for later interpolation
pressure$TIMESTAMP <- as.POSIXct(pressure$TIMESTAMP, tz = "UTC", format="%Y-%m-%d %H:%M:%OS")
pressure$BaroPress_hPa <- as.double(pressure$BaroPress_hPa)

# plot wind
met$TIMESTAMP <- as.POSIXct(met$TIMESTAMP, tz = "UTC", format="%Y-%m-%d %H:%M:%OS")
met <- met[-1,]
met <- met[-1,]
met$WindSpd <- as.numeric(met$WindSpd)
met$WindDir <- as.numeric(met$WindDir)
met$AirTemp <- as.numeric(met$AirTemp)

ggplot(met, aes(x = TIMESTAMP, y = WindSpd)) +  geom_point() +  theme_minimal()
ggplot(met, aes(x = TIMESTAMP, y = WindDir)) +  geom_point() +  theme_minimal()
ggplot(met, aes(x = TIMESTAMP, y = AirTemp)) +  geom_point() +  theme_minimal()

```

```{r}

ggplot(combined, aes(x = datetime_utc, y = temperature, color = temperature_flag)) +
  geom_point() +
  theme_minimal()

ggplot(combined, aes(x = datetime_utc, y = salinity, color = salinity_flag)) +
  geom_point() +
  theme_minimal()

ggplot(combined, aes(x = datetime_utc, y = oxygen_umol_kg)) +
  geom_point() +
  theme_minimal()

ggplot(combined, aes(x = datetime_utc, y = ph_corrected, color = ph_flag)) +
  geom_point() +
  theme_minimal()

ggplot(combined, aes(x = datetime_utc, y = rho_ppb, color = rho_flag)) +
  geom_point() +
  theme_minimal()

ggplot(pressure, aes(x = TIMESTAMP, y = BaroPress_hPa)) +
  geom_line() +
  theme_minimal()

```
```{r}

# set values with bad flags to NA

combined <- combined |>
  mutate(temperature = replace(temperature, temperature_flag == "4", NA)) |>
  mutate(salinity = replace(salinity, salinity_flag == "4", NA)) |>
  mutate(ph_corrected = replace(ph_corrected, ph_flag == "4", NA)) |>
  mutate(rho_ppb = replace(rho_ppb, rho_flag == "4", NA)) 

ggplot(combined, aes(x = datetime_utc, y = temperature, color = temperature_flag)) +
  geom_point() +
  theme_minimal()

ggplot(combined, aes(x = datetime_utc, y = salinity, color = salinity_flag)) +
  geom_point() +
  theme_minimal()

ggplot(combined, aes(x = datetime_utc, y = ph_corrected, color = ph_flag)) +
  geom_point() +
  theme_minimal()

ggplot(combined, aes(x = datetime_utc, y = rho_ppb, color = rho_flag)) +
  geom_point() +
  theme_minimal()

```


```{r}

# read in GO data
GOfiles <- dir(here("loc-02-input/pco2_raw"), "*.txt") # get file names

GO_LOC02 <- GOfiles %>% map_dfr(~ read_tsv(here("loc-02-input/pco2_raw", .), show_col_types = FALSE, ))

```

```{r}

# handle date and time columns
# combine date and time
GO_LOC02$PcDate <- as.character(GO_LOC02$PcDate) 
GO_LOC02$PcTime <- as.character(GO_LOC02$PcTime) 
#GO_LOC02$PcTime <- as.character(GO_LOC02$PcTime) 
GO_LOC02$date_time <- paste(GO_LOC02$PcDate, GO_LOC02$PcTime)
GO_LOC02$date_time_utc <- as.POSIXct(GO_LOC02$date_time, tz = "UTC", format="%d/%m/%y %H:%M:%OS")

# plot a few variables
ggplot(GO_LOC02, aes(x = date_time_utc, y = EquPress)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = date_time_utc, y = EquTemp)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = date_time_utc, y = CO2ppm)) +
  geom_point() +
  theme_minimal()

# pCO2 data start at 2025-08-12 16:49, TSG combined data set starts at 2025-08-13 07:37
# are there SSS and SST data from the interval in between to allow pCO2 calculations?

# remove lines without TSG
GO_LOC02 <- GO_LOC02 |> filter(date_time_utc > "2025-08-13 07:37:00") |>
  mutate(EquTemp = case_when(Error == 304 ~ 21.50, TRUE ~ EquTemp))
# data set now begins with standard run at start of TSG data
# initial round of stds and first ATM were missing equilibrator temperature; filled these in with temperature of 21.50 (temp at first EQU measurements) to avoid having to flag as bad in pCO2sys 

# plot again
ggplot(GO_LOC02, aes(x = date_time_utc, y = EquPress)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = date_time_utc, y = EquTemp)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = date_time_utc, y = CO2ppm)) +
  geom_point() +
  theme_minimal()

```

# Interpolate TSG data to GO timestamps

```{r}

# using function "approx" to interpolate TSG data to GO timestamps
# rule argument: an integer (of length 1 or 2) describing how interpolation is to take place outside the interval [min(x), max(x)]. If rule is 1 then NAs are returned for such points and if it is 2, the value at the closest data extreme is used. Use, e.g., rule = 2:1, if the left and right side extrapolation should differ.
# method argument: specifies the interpolation method to be used. Choices are "linear" or "constant".


lat <- data.frame(approx(combined$datetime_utc, combined$latitude, xout = GO_LOC02$date_time_utc, rule = 2, method = "linear"))
latitude <- lat$y 

lon <- data.frame(approx(combined$datetime_utc, combined$longitude, xout = GO_LOC02$date_time_utc, rule = 2, method = "linear"))
longitude <- lon$y 

dye <- data.frame(approx(combined$datetime_utc, combined$rho_ppb, xout = GO_LOC02$date_time_utc, rule = 2, method = "linear"))
rhodamine_ppb <- dye$y 

temperature <- data.frame(approx(combined$datetime_utc, combined$temperature, xout = GO_LOC02$date_time_utc, rule = 2, method = "linear"))
temperature_c  <- temperature$y 

sal <- data.frame(approx(combined$datetime_utc, combined$salinity, xout = GO_LOC02$date_time_utc, rule = 2, method = "linear"))
salinity_psu <- sal$y 

ph <- data.frame(approx(combined$datetime_utc, combined$ph_corrected, xout = GO_LOC02$date_time_utc, rule = 2, method = "linear"))
ph_corrected <- ph$y 

# alk <- data.frame(approx(combined$datetime_utc, combined$Corrected_TA_umol_kg_, xout = GO_LOC02$date_time_utc, rule = 2, method = "linear"))
# alkalinity_umolkg <- alk$y 

press <- data.frame(approx(pressure$TIMESTAMP, pressure$BaroPress_hPa, xout = GO_LOC02$date_time_utc, rule = 1, method = "linear"))
atm_pressure_hPa <- press$y 

winds <- data.frame(approx(met$TIMESTAMP, met$WindSpd, xout = GO_LOC02$date_time_utc, rule = 1, method = "linear"))
wind_spd <- winds$y

windd <- data.frame(approx(met$TIMESTAMP, met$WindDir, xout = GO_LOC02$date_time_utc, rule = 1, method = "linear"))
wind_dir <- windd$y

airt <- data.frame(approx(met$TIMESTAMP, met$WindSpd, xout = GO_LOC02$date_time_utc, rule = 1, method = "linear"))
air_temp <- airt$y

comp <- data.frame(approx(met$TIMESTAMP, met$WindSpd, xout = GO_LOC02$date_time_utc, rule = 1, method = "linear"))
compass <- comp$y

GO_LOC02 <- cbind(GO_LOC02, latitude, longitude, atm_pressure_hPa, rhodamine_ppb, temperature_c, salinity_psu, ph_corrected, wind_spd, wind_dir, air_temp, compass) #, alkalinity_umolkg)

```
# Inspect interpolated ancillary data

```{r}

ggplot(GO_LOC02, aes(x = date_time_utc, y = temperature_c)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = date_time_utc, y = salinity_psu)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = date_time_utc, y = atm_pressure_hPa)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = date_time_utc, y = rhodamine_ppb)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = date_time_utc, y = ph_corrected)) +
  geom_point() +
  theme_minimal()

ggplot(GO_LOC02, aes(x = longitude, y = latitude, color = ph_corrected)) +
  geom_point() +
  theme_minimal()

# ggplot(GO_LOC02, aes(x = date_time_utc, y = alkalinity_umolkg)) +
#   geom_point() +
#   theme_minimal()

```
# Adjust columns and write csv

```{r}

GO_LOC02 <- GO_LOC02 |>
  #filter(Type != 'SHUT DOWN') |> # this removes SHUT DOWN rows and error message rows (that have NA in all data cols)
  select(-date_time, -'N/A') |>
  relocate(date_time_utc, .before = Type) |>
  relocate(latitude, .before = Type) |>
  relocate(longitude, .before = Type) 

# calculate absolute equilibrator pressure
GO_LOC02$EquPressCalc <- GO_LOC02$atm_pressure_hPa + GO_LOC02$EquPress

```

# Investigate standards

```{r}

ATM <- GO_LOC02 |>  filter(Type == 'ATM' | Type == 'ATM-DRAIN') 
std1 <- GO_LOC02 |>  filter(Type == 'STD1' | Type == 'STD1-DRAIN') 
std2 <- GO_LOC02 |>  filter(Type == 'STD2' | Type == 'STD2-DRAIN') 
std3 <- GO_LOC02 |>  filter(Type == 'STD3' | Type == 'STD3-DRAIN') 
std4 <- GO_LOC02 |>  filter(Type == 'STD4' | Type == 'STD4-DRAIN') 
equ <- GO_LOC02 |>  filter(Type == 'EQU' | Type == 'EQU-DRAIN') 

a <- ggplot(ATM, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() + geom_line() + theme_minimal() + labs(title='ATM')
ggplotly(a)
#ggplot(ATM, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() + theme_minimal() + labs(title='ATM')
s1 <-ggplot(std1, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() + geom_line() + theme_minimal() + labs(title='STD1 0 ppm')
ggplotly(s1)
#ggplot(std1, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() +  theme_minimal() + labs(title='STD1 0 ppm')
s2 <-ggplot(std2, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() + geom_line() + theme_minimal()+ labs(title='STD2 426.36 ppm')
ggplotly(s2)
#ggplot(std2, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() +  theme_minimal()+ labs(title='STD2 426.36 ppm')
s3 <-ggplot(std3, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() + geom_line() + theme_minimal()+ labs(title='STD3 547.63 ppm')
ggplotly(s3)
#ggplot(std3, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() +  theme_minimal()+ labs(title='STD3 547.63 ppm')
s4 <-ggplot(std4, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() + geom_line() + theme_minimal()+ labs(title='STD4 1234.58 ppm')
ggplotly(s4)
#ggplot(std4, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() +  theme_minimal()+ labs(title='STD4 1234.58 ppm')
sw <-ggplot(equ, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() + geom_line() +  theme_minimal()+ labs(title='Seawater')
ggplotly(sw)
#ggplot(equ, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() +  theme_minimal()+ labs(title='Seawater')

```
```{r}

# 

stds <- GO_LOC02 |>  filter(Type == 'STD1' | Type == 'STD1-DRAIN' | Type == 'STD2' | Type == 'STD2-DRAIN' | Type == 'STD3' | Type == 'STD3-DRAIN' | Type == 'STD4' | Type == 'STD4-DRAIN') 

std_label <- stds$Type
std_label <- as.data.frame(std_label)

write_csv(std_label, here('loc-02-input/sequence-list.csv'))

# manually edit sequence :)

sequence <- read_csv(here('loc-02-input/sequence.csv')) 
stds <- cbind(stds, sequence)
stds <- stds |> relocate(sequence, .after = Type)

stds <- stds |> select(date_time_utc, latitude, longitude, Type, sequence, CO2StdValue, CO2ppm)

stdavg <- stds |> group_by(sequence) |> summarise(avg = mean(CO2ppm))

first_time <- stds |> group_by(sequence) |> summarise(first(date_time_utc)) |> select(-sequence)

stdavg <- cbind(stdavg, first_time)
stdavg <- stdavg |> 
  rename(date_time_utc = "first(date_time_utc)") |>
  rename(seq_first = sequence) |>
  rename(CO2_std_avg = avg)

stds <- left_join(stds, stdavg)
GO_LOC02 <- left_join(GO_LOC02, stds)

# flag some measurements to be excluded?
# something weird when a single meas was followed by 3? shutdown?

```


```{r}

std1a <- stds |>  filter(Type == 'STD1' | Type == 'STD1-DRAIN') 
std2a <- stds |>  filter(Type == 'STD2' | Type == 'STD2-DRAIN') 
std3a <- stds |>  filter(Type == 'STD3' | Type == 'STD3-DRAIN') 
std4a <- stds |>  filter(Type == 'STD4' | Type == 'STD4-DRAIN') 

s1a <- ggplot(std1a, aes(x = date_time_utc, y = CO2_std_avg)) +  geom_point() +  theme_minimal() + labs(title='STD1 0 ppm')
ggplotly(s1a)
s2a <-ggplot(std2a, aes(x = date_time_utc, y = CO2_std_avg)) +  geom_point() +  theme_minimal()+ labs(title='STD2 426.36 ppm')
ggplotly(s2a)
s3a <-ggplot(std3a, aes(x = date_time_utc, y = CO2_std_avg)) +  geom_point() +  theme_minimal()+ labs(title='STD3 547.63 ppm')
ggplotly(s3a)
s4a <-ggplot(std4a, aes(x = date_time_utc, y = CO2_std_avg)) +  geom_point() +  theme_minimal()+ labs(title='STD4 1234.58 ppm')
ggplotly(s4a)

```
```{r}

#write.csv(GO_LOC02, here('loc-02-for-pco2sys/GO_LOC02_to_flag.csv'), row.names = FALSE)

# manually add flags

flagged <- read_csv(here('loc-02-for-pco2sys/GO_LOC02_flagged.csv'))

flagged <- flagged |>
  mutate(Flag_manual = case_when(is.na(Flag_manual) ~ 2, TRUE ~ Flag_manual))

flagged$PcDate <- as.character(flagged$PcDate) 
flagged$PcTime <- as.character(flagged$PcTime) 
flagged$date_time <- paste(flagged$PcDate, flagged$PcTime)
flagged$date_time_utc <- as.POSIXct(flagged$date_time, tz = "UTC", format="%d/%m/%y %H:%M:%OS")

flagged <- flagged |> select(-date_time)

```

```{r}

ATMf <- flagged |>  filter(Type == 'ATM' | Type == 'ATM-DRAIN')
std1f <- flagged |>  filter(Type == 'STD1' | Type == 'STD1-DRAIN') 
std2f <- flagged |>  filter(Type == 'STD2' | Type == 'STD2-DRAIN') 
std3f <- flagged |>  filter(Type == 'STD3' | Type == 'STD3-DRAIN') 
std4f <- flagged |>  filter(Type == 'STD4' | Type == 'STD4-DRAIN') 
equf <- flagged |>  filter(Type == 'EQU' | Type == 'EQU-DRAIN') 

atmf <- ggplot(ATMf, aes(x = date_time_utc, y = CO2ppm, color = Flag_manual)) +  geom_point() + geom_line() + theme_minimal() + labs(title='ATM')
atmf <- ggplot(ATMf, aes(x = date_time_utc, y = CO2ppm, color = Flag_manual)) +  geom_point() + theme_minimal() + labs(title='ATM')
ggplotly(atmf)

s1f <-ggplot(std1f, aes(x = date_time_utc, y = CO2ppm, color = Flag_manual)) +  geom_point() + theme_minimal() + labs(title='STD1 0 ppm')
ggplotly(s1f)

s2f <-ggplot(std2f, aes(x = date_time_utc, y = CO2ppm, color = Flag_manual)) + geom_point() + theme_minimal()+ labs(title='STD2 426.36 ppm')
ggplotly(s2f)

s3f <-ggplot(std3f, aes(x = date_time_utc, y = CO2ppm, color = Flag_manual)) +  geom_point() + theme_minimal()+ labs(title='STD3 547.63 ppm')
ggplotly(s3f)

s4f <-ggplot(std4f, aes(x = date_time_utc, y = CO2ppm, color = Flag_manual)) +  geom_point() + theme_minimal()+ labs(title='STD4 1234.58 ppm')
ggplotly(s4f)

swf <-ggplot(equf, aes(x = date_time_utc, y = CO2ppm, color = Flag_manual)) +  geom_point() +  theme_minimal()+ labs(title='Seawater')
ggplotly(swf)

swf <-ggplot(equf, aes(x = date_time_utc, y = CO2ppm, color = temperature_c)) +  geom_point() +  theme_minimal()+ labs(title='Seawater') 
ggplotly(swf) 

swp <-ggplot(equf, aes(x = date_time_utc, y = CO2ppm, color = ph_corrected)) +  geom_point() +  theme_minimal()+ labs(title='Seawater') 
ggplotly(swp) 

q <-ggplot(equf, aes(x = date_time_utc, y = EquH2OFlow)) +  geom_point() +  theme_minimal()+ labs(title='H2O Flow') 
ggplotly(q)

eq <- ggplot(equf, aes(x = EquH2OFlow, y = CO2ppm, color = EquTemp)) +  geom_point() +  theme_minimal()+ labs(title='H2O Flow') 
ggplotly(eq)

sq <- ggplot(equf, aes(x = EquH2OFlow, y = CO2ppm, color = temperature_c)) +  geom_point() +  theme_minimal()+ labs(title='H2O Flow') 
ggplotly(sq)

```

```{r}

# 

stds <- flagged |>  filter(Type == 'STD1' | Type == 'STD1-DRAIN' | Type == 'STD2' | Type == 'STD2-DRAIN' | Type == 'STD3' | Type == 'STD3-DRAIN' | Type == 'STD4' | Type == 'STD4-DRAIN') 

stds <- cbind(stds, sequence)
stds <- stds |> relocate(sequence, .after = Type)

stds <- stds |>  filter(Flag_manual == 3 | Flag_manual == 2)

stds <- stds |> select(date_time_utc, latitude, longitude, Type, sequence, Flag_manual, CO2StdValue, CO2ppm)

stdavg <- stds |> group_by(sequence) |> summarise(avg = mean(CO2ppm))

first_time <- stds |> group_by(sequence) |> summarise(first(date_time_utc)) |> select(-sequence)

stdavg <- cbind(stdavg, first_time)
stdavg <- stdavg |> 
  rename(date_time_utc = "first(date_time_utc)") |>
  rename(seq_first = sequence) |>
  rename(CO2_std_avg = avg)

stds <- left_join(stds, stdavg)

# inspect 

# join averaged standards to full data set
stds <- stds |> select(date_time_utc, CO2_std_avg)
flagged <- left_join(flagged, stds)

# replace CO2 measured value with average for each group of standards
flagged <- flagged |>
  mutate(CO2ppm = case_when(CO2StdValue != "NA" ~ CO2_std_avg,
                            is.na(CO2StdValue) ~ CO2ppm))

```

```{r}

# plot averaged standards again

std1fa <- flagged |>  filter(Type == 'STD1' | Type == 'STD1-DRAIN') 
std2fa <- flagged |>  filter(Type == 'STD2' | Type == 'STD2-DRAIN') 
std3fa <- flagged |>  filter(Type == 'STD3' | Type == 'STD3-DRAIN') 
std4fa <- flagged |>  filter(Type == 'STD4' | Type == 'STD4-DRAIN') 

s1fa <-ggplot(std1fa, aes(x = date_time_utc, y = CO2_std_avg)) +  geom_point() + theme_minimal() + labs(title='STD1 0 ppm')
ggplotly(s1fa)

s2fa <-ggplot(std2fa, aes(x = date_time_utc, y = CO2_std_avg)) + geom_point() + theme_minimal()+ labs(title='STD2 426.36 ppm')
ggplotly(s2fa)

s3fa <-ggplot(std3fa, aes(x = date_time_utc, y = CO2_std_avg)) +  geom_point() + theme_minimal()+ labs(title='STD3 547.63 ppm')
ggplotly(s3fa)

s4fa <-ggplot(std4fa, aes(x = date_time_utc, y = CO2_std_avg)) +  geom_point() + theme_minimal()+ labs(title='STD4 1234.58 ppm')
ggplotly(s4fa)

```


```{r}

ATM_sequence <- read_csv(here('loc-02-input/atm_sequence.csv'))

ATMf <- flagged |>  filter(Type == 'ATM' | Type == 'ATM-DRAIN')

ATMf <- cbind(ATMf, ATM_sequence)

ATMf$rho_log <- as.numeric(NA)
ATMf <- ATMf |> mutate(rho_log = log10(rhodamine_ppb+0.5)) # for plotting

atmf <- ggplot(ATMf, aes(x = date_time_utc, y = CO2ppm, color = Flag_manual)) +  geom_point() + theme_minimal() + labs(title='ATM')
ggplotly(atmf)

ATMf <- ATMf |>  filter(Flag_manual == 2)
atmrho <- ggplot(ATMf, aes(x = date_time_utc, y = CO2ppm, color = rho_log)) +  geom_point() + theme_minimal() + labs(title='ATM')
ggplotly(atmrho)
atmf <- ggplot(ATMf, aes(x = date_time_utc, y = CO2ppm)) +  geom_point() + theme_minimal() + labs(title='ATM')
ggplotly(atmf)

ggplot(ATMf, aes(x = date_time_utc, y = CO2ppm)) + geom_line()+ geom_point() + theme_minimal() + labs(title='ATM')

```


```{r}

ggplot(equf, aes(x = date_time_utc, y = CO2ppm, color = "water")) + geom_point()+
    geom_point(data = ATMf, aes(x = date_time_utc, y = CO2ppm, color = "air"))  +
  ylim(400, 500)

equf$rho_log <- as.numeric(NA)
equf <- equf |> mutate(rho_log = log10(rhodamine_ppb+2))
rh <- ggplot(equf, aes(x = date_time_utc, y = rho_log)) + geom_point() +geom_line()
ggplotly(rh)

# ggplot(equf, aes(x = date_time_utc, y = CO2ppm, color = rho_log)) + geom_point() +
#   ylim(400, 500)
# 
# p<-ggplot(equf, aes(x = date_time_utc, y = CO2ppm, color = rho_log)) + geom_point()
# ggplotly(p)

l<-ggplot(equf, aes(x = date_time_utc, y = CO2ppm, color = rho_log)) + geom_point() +scale_color_gradient2(low = "blue",mid = "yellow",high = "red", midpoint = 1.2)
ggplotly(l)

# aw <- ggplot(equf, aes(x = date_time_utc, y = CO2ppm, color = rho_log)) + geom_point()+ scale_color_gradient2(low = "blue",mid = "yellow",high = "red", midpoint = 1.2)+ geom_point(data = ATMf, aes(x = date_time_utc, y = CO2ppm))  
# ggplotly(aw)

```


```{r}

# average each group of ATM measurements and add to flagged dataframe

atmavg <- ATMf |> group_by(atm_sequence) |> summarise(CO2_atm_avg = mean(CO2ppm))

ATMf <- left_join(ATMf, atmavg)

#first_atm <- ATMf |> group_by(atm_sequence) |> summarise(first(date_time_utc)) |> select(-atm_sequence)
#atmavg <- cbind(atmavg, first_atm)

# atmavg <- atmavg |>
#   rename(date_time_utc = "first(date_time_utc)") |>
#   rename(seq_first = atm_sequence) |>
#   rename(CO2_atm_avg = avg)

ggplot(ATMf, aes(x = date_time_utc, y = CO2ppm, color = "all")) + geom_point()+
    geom_point(data = ATMf, aes(x = date_time_utc, y = CO2_atm_avg, color = "average"))  

# join averaged standards to full data set
ATMf <- ATMf |> 
  select(date_time_utc, CO2ppm, CO2_atm_avg) |>
  rename(ATM_meas_CO2_ppm = CO2ppm) |>
  rename(ATM_avg_CO2_ppm = CO2_atm_avg)

flagged_all <- left_join(flagged, ATMf) 

# replace CO2 measured value with average for each group of standards
flagged_all <- flagged_all |>
  mutate(CO2ppm = case_when(Type == "ATM" ~ ATM_avg_CO2_ppm,
                            Type != "ATM" ~ CO2ppm)) |>
  mutate(EquTemp = case_when(Error == 304 ~ 21.50, TRUE ~ EquTemp)) |>
  mutate(EquTemp = case_when(date_time_utc == "2025-08-13 08:28:16" ~ 21.50, TRUE ~ EquTemp))

flagged_all <- flagged_all |> filter(!is.na(CO2ppm))

```

```{r}

# write file to ingest into pCO2sys

write.csv(flagged_all, here('loc-02-for-pco2sys/GO_LOC02.csv'), row.names = FALSE, na = "NaN")

```

# pco2sys processing notes  

```{r}

# in R, flagged/excluded bad and then averaged good measurements of STDS and ATM

# flagged as bad 4 instances of low H2O flow followed by CO2 spike and one single measurement where connection was lost
# then interpolated these. In Final file, manually edited flag to 3 and added QC subflag

# calculated absolute equilibrator pressure in R by adding differential eq pressure to atm pressure. 
# Then assigned this to LICOR pressure and EQU pressure in pCO2sys and unchecked the differential box. 
# otherwise, pCO2sys can't find EQU Pressure (calc) and delta P

# no temperature time offset between SST and EQU temp

```
# Merge met and CO2 data with full underway data set

```{r}

underway <- read_csv(here('loc-02-input/loc02_uw_qc.csv')) 
fco2 <- read_csv(here('loc-02-pco2sys-output/LOC_02_Final.csv'), skip = 4) 

fco2$date <- dmy(fco2$DATE_UTC__ddmmyyyy)
fco2$datetime_utc <- paste(fco2$date, fco2$`TIME_UTC_hh:mm:ss`)

fco2$datetime_utc <- as.POSIXct(fco2$datetime_utc, tz = "UTC", format="%Y-%m-%d %H:%M:%OS")

fco2 <- fco2 |>
  rename(latitude = LAT_dec_degree) |>
  rename(longitude = LONG_dec_degree) |>
  rename(PRES_ATM_SSP_hPa = `PRES_ATM@SSP_hPa`) |>
  rename(fCO2_SW_SST_uatm = `fCO2_SW@SST_uatm`) |>
  select(datetime_utc, latitude, longitude, xCO2_EQU_ppm, xCO2_ATM_ppm, xCO2_ATM_interpolated_ppm, PRES_EQU_hPa, PRES_ATM_SSP_hPa, TEMP_EQU_C, SST_C, SAL_permil, fCO2_SW_SST_uatm, fCO2_ATM_interpolated_uatm, dfCO2_uatm, WOCE_QC_FLAG, QC_SUBFLAG)

fco2$xCO2_EQU_ppm <- replace(fco2$xCO2_EQU_ppm, fco2$xCO2_EQU_ppm == -999, NaN)
fco2$xCO2_ATM_ppm <- replace(fco2$xCO2_ATM_ppm, fco2$xCO2_ATM_ppm == -999, NaN)
fco2$xCO2_ATM_interpolated_ppm <- replace(fco2$xCO2_ATM_interpolated_ppm, fco2$xCO2_ATM_interpolated_ppm == -999, NaN)
fco2$fCO2_SW_SST_uatm <- replace(fco2$fCO2_SW_SST_uatm, fco2$fCO2_SW_SST_uatm == -999, NaN)
fco2$fCO2_ATM_interpolated_uatm <- replace(fco2$fCO2_ATM_interpolated_uatm, fco2$fCO2_ATM_interpolated_uatm == -999, NaN)
fco2$dfCO2_uatm <- replace(fco2$dfCO2_uatm, fco2$dfCO2_uatm == -999, NaN)

fco2$PRES_EQU_hPa <- replace(fco2$PRES_EQU_hPa, fco2$PRES_EQU_hPa == -999, NaN)
fco2$PRES_ATM_SSP_hPa <- replace(fco2$PRES_ATM_SSP_hPa, fco2$PRES_ATM_SSP_hPa == -999, NaN)
fco2$TEMP_EQU_C <- replace(fco2$TEMP_EQU_C, fco2$TEMP_EQU_C == -999, NaN)
fco2$SST_C <- replace(fco2$SST_C, fco2$SST_C == -999, NaN)
fco2$SAL_permil <- replace(fco2$SAL_permil, fco2$SAL_permil == -999, NaN)

# round fco2 timestamp to nearest 2 sec to make timestamps match 
fco2$rounded_time <- round_date(fco2$datetime_utc, "2s")
fco2 <- fco2 |>
  select(-datetime_utc, -latitude, -longitude)|>
  rename(datetime_utc = rounded_time) 

underway_fco2 <- full_join(underway, fco2)

# met <- met |>
#   rename(datetime_utc = TIMESTAMP) #|>
#   #rename(datetime_utc = date_time_utc)

underway_all <- full_join(underway_fco2, met)

underway_all <- underway_all[order(underway_all$datetime_utc), ]

ggplot(underway_all, aes(x = datetime_utc, y = WindSpd)) +  geom_point() +  theme_minimal()
ggplot(underway_all, aes(x = datetime_utc, y = fCO2_SW_SST_uatm)) +  geom_point() +  theme_minimal()
ggplot(underway_all, aes(x = datetime_utc, y = xCO2_EQU_ppm)) +  geom_point() +  theme_minimal()

#underway_all <- gsub("-999", "NaN", underway_all)

write.csv(underway_all, here('loc-02-output/LOC02_underway_sensors_fCO2_met.csv'), row.names = FALSE, na = "NaN", fileEncoding = "UTF-8")

```








